Name:           ros-melodic-nodelet
Version:        1.9.16
Release:        0%{?dist}
Summary:        ROS nodelet package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/nodelet
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       libuuid-devel
Requires:       ros-melodic-bondcpp
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-pluginlib >= 1.10.0
Requires:       ros-melodic-rosconsole
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rospy
Requires:       ros-melodic-std-msgs
BuildRequires:  boost-devel
BuildRequires:  libuuid-devel
BuildRequires:  ros-melodic-bondcpp
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules >= 0.3.2
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-pluginlib >= 1.10.0
BuildRequires:  ros-melodic-rosconsole
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-std-msgs

%description
The nodelet package is designed to provide a way to run multiple algorithms in
the same process with zero copy transport between algorithms. This package
provides both the nodelet base class needed for implementing a nodelet, as well
as the NodeletLoader class used for instantiating nodelets.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Apr 27 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.9.16-0
- Autogenerated by Bloom

* Fri Mar 16 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.9.15-0
- Autogenerated by Bloom

* Thu Mar 15 2018 Mikael Arguedas <mikael@osrfoundation.org> - 1.9.14-0
- Autogenerated by Bloom

